### ISSUE TITLE
AsyncWriterThread takes 60% CPU time

### ISSUE THREAD

**Issue by micxiaoc** [ros2/rmw_fastrtps#611]
## Bug report

**Required Info:**

- Operating System:
  - Linux
- Installation type:
  - foxy
- Version or commit hash:
  - not sure
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
When using rosbridge, asyncwriterthread will be generated after a few hours, which will occupy a high CPU and remain at 60%. Is there any way to reduce the CPU on foxy

#### Expected behavior
CPU can remain stable
#### Actual behavior
Asyncwriterthread raises CPU
#### Additional information

----

**Comment by EduPonz** [comment]
Hi,

Each Participant holds an `AsyncWriterThread` instance that is used to:

1. Send user data coming from asynchronous writers (as all ROS 2 writers are by default).
2. Take care of re-sendings in the case of reliable writers.
3. Take care of feeding data to late joiners which DurabilityQosPolicy is other than `VOLATILE`.

> asyncwriterthread will be generated after a few hours

Because of the previous, I'm not sure I understand what you mean with this; the async thread may de stalling but it should always exist.

Could you try to reproduce in 2.1.x?

**Comment by clalancette** [comment]
No response in a year here, so closing this out.  If you are still having problems, please open a new issue.
